export interface District {
  id: string
  name: string
  arabic: string
}

export const JEDDAH_DISTRICTS: District[] = [
  { id: "al-naeem", name: "Al-Naeem", arabic: "النعيم" },
  { id: "al-balad", name: "Al-Balad", arabic: "البلد" },
  { id: "al-hamra", name: "Al-Hamra", arabic: "الحمراء" },
  { id: "al-rawdah", name: "Al-Rawdah", arabic: "الروضة" },
  { id: "al-salamah", name: "Al-Salamah", arabic: "السلامة" },
  { id: "al-zahra", name: "Al-Zahra", arabic: "الزهراء" },
  { id: "al-andalus", name: "Al-Andalus", arabic: "الأندلس" },
  { id: "al-shati", name: "Al-Shati", arabic: "الشاطئ" },
  { id: "al-marjan", name: "Al-Marjan", arabic: "المرجان" },
  { id: "downtown", name: "Downtown", arabic: "وسط المدينة" },
  { id: "westside", name: "Westside", arabic: "الجانب الغربي" },
  { id: "north-obhur", name: "North Obhur", arabic: "أبحر الشمالية" },
  { id: "south-obhur", name: "South Obhur", arabic: "أبحر الجنوبية" },
  { id: "al-basateen", name: "Al-Basateen", arabic: "البساتين" },
  { id: "al-faisaliyah", name: "Al-Faisaliyah", arabic: "الفيصلية" },
  { id: "al-rehab", name: "Al-Rehab", arabic: "الرحاب" },
  { id: "al-safa", name: "Al-Safa", arabic: "الصفا" },
  { id: "al-aziziyah", name: "Al-Aziziyah", arabic: "العزيزية" },
  { id: "ash-sharafiyah", name: "Ash Sharafiyah", arabic: "الشرفية" },
  { id: "al-baghdadiyah", name: "Al-Baghdadiyah", arabic: "البغدادية" },
  { id: "al-khalidiyah", name: "Al-Khalidiyah", arabic: "الخالدية" },
  { id: "al-muhammadiyah", name: "Al-Muhammadiyah", arabic: "المحمدية" },
  { id: "al-thaalba", name: "Al-Thaalba", arabic: "الثعالبة" },
  { id: "al-bawadi", name: "Al-Bawadi", arabic: "البوادي" },
  { id: "al-fayhaa", name: "Al-Fayhaa", arabic: "الفيحاء" },
  { id: "al-jameah", name: "Al-Jameah", arabic: "الجامعة" },
  { id: "al-waziriyah", name: "Al-Waziriyah", arabic: "الوزيرية" },
  { id: "al-sabeel", name: "Al-Sabeel", arabic: "السبيل" },
  { id: "al-kandra", name: "Al-Kandra", arabic: "الكندرة" },
  { id: "al-naseem", name: "Al-Naseem", arabic: "النسيم" },
  { id: "al-manar", name: "Al-Manar", arabic: "المنار" },
  { id: "al-sheraa", name: "Al-Sheraa", arabic: "الشراع" },
  { id: "al-ferdous", name: "Al-Ferdous", arabic: "الفردوس" },
  { id: "al-harazat", name: "Al-Harazat", arabic: "الحرازات" },
  { id: "al-rowais", name: "Al-Rowais", arabic: "الرويس" },
  { id: "al-sharafiyah-al-gharbiyah", name: "Al-Sharafiyah Al-Gharbiyah", arabic: "الشرفية الغربية" },
  { id: "al-salehiyah", name: "Al-Salehiyah", arabic: "الصالحية" },
  { id: "al-sawaid", name: "Al-Sawaid", arabic: "الصوائد" },
  { id: "al-taiaser", name: "Al-Taiaser", arabic: "التياسر" },
  { id: "al-buhairat", name: "Al-Buhairat", arabic: "البحيرات" },
  { id: "al-ajaweed", name: "Al-Ajaweed", arabic: "الأجاويد" },
  { id: "al-nakheel", name: "Al-Nakheel", arabic: "النخيل" },
  { id: "al-montazahat", name: "Al-Montazahat", arabic: "المنتزهات" },
  { id: "al-murjan", name: "Al-Murjan", arabic: "المرجان" },
  { id: "al-worood", name: "Al-Worood", arabic: "الورود" },
  { id: "al-rabwah", name: "Al-Rabwah", arabic: "الربوة" },
  { id: "al-corniche", name: "Al-Corniche", arabic: "الكورنيش" },
  { id: "al-ameer-fawaz", name: "Al-Ameer Fawaz", arabic: "الأمير فواز" },
  { id: "al-ameer-abdullah-al-faisal", name: "Al-Ameer Abdullah Al-Faisal", arabic: "الأمير عبدالله الفيصل" },
  { id: "al-sahel", name: "Al-Sahel", arabic: "الساحل" },
  { id: "al-lulu", name: "Al-Lulu", arabic: "اللؤلؤ" },
  { id: "al-ajwad", name: "Al-Ajwad", arabic: "الأجواد" },
  { id: "al-mahrajan", name: "Al-Mahrajan", arabic: "المهرجان" },
  { id: "al-wahah", name: "Al-Wahah", arabic: "الواحة" },
  { id: "al-yaqoot", name: "Al-Yaqoot", arabic: "الياقوت" },
  { id: "al-meshrefa", name: "Al-Meshrefa", arabic: "المشرفة" },
  { id: "al-mohammadiyah-aljanoubiyah", name: "Al-Mohammadiyah Al-Janoubiyah", arabic: "المحمدية الجنوبية" },
  { id: "al-jamea", name: "Al-Jamea", arabic: "الجامعة" },
  { id: "al-narjis", name: "Al-Narjis", arabic: "النرجس" },
  { id: "al-rabwa", name: "Al-Rabwa", arabic: "الربوة" },
  { id: "al-hindawiyah", name: "Al-Hindawiyah", arabic: "الهنداوية" },
  { id: "al-sultan", name: "Al-Sultan", arabic: "السلطان" },
  { id: "al-mina", name: "Al-Mina", arabic: "الميناء" },
  { id: "al-rihab", name: "Al-Rihab", arabic: "الرحاب" },
  { id: "al-amir-majed", name: "Al-Amir Majed", arabic: "الأمير ماجد" },
  { id: "al-mohamadiyah-ash-shamaliyah", name: "Al-Mohamadiyah Ash-Shamaliyah", arabic: "المحمدية الشمالية" },
  { id: "al-samer", name: "Al-Samer", arabic: "السامر" },
  { id: "al-fairoziyah", name: "Al-Fairoziyah", arabic: "الفيروز" },
  { id: "al-sanabel", name: "Al-Sanabel", arabic: "السنابل" },
  { id: "al-ahmar", name: "Al-Ahmar", arabic: "الأحمر" },
  { id: "briman", name: "Briman", arabic: "بريمان" },
  { id: "al-hamdaniyah", name: "Al-Hamdaniyah", arabic: "الحمدانية" },
  { id: "al-sharafieh", name: "Al-Sharafieh", arabic: "الشرفية" },
  { id: "al-morooj", name: "Al-Morooj", arabic: "المروج" },
  { id: "al-tawfiq", name: "Al-Tawfiq", arabic: "التوفيق" },
  { id: "al-mahjar", name: "Al-Mahjar", arabic: "المحجر" },
  { id: "al-samer-al-jadeed", name: "Al-Samer Al-Jadeed", arabic: "السامر الجديد" },
  { id: "al-baghlieh", name: "Al-Baghlieh", arabic: "البغلية" },
  { id: "ghulail", name: "Ghulail", arabic: "غليل" },
  { id: "al-nozha", name: "Al-Nozha", arabic: "النزهة" },
  { id: "al-quds", name: "Al-Quds", arabic: "القدس" },
  { id: "al-shafaa", name: "Al-Shafaa", arabic: "الشفاء" },
  { id: "al-shatee", name: "Al-Shatee", arabic: "الشاطئ" },
  { id: "al-shamaliyah", name: "Al-Shamaliyah", arabic: "الشمالية" },
  { id: "madaen-al-fahd", name: "Madaen Al-Fahd", arabic: "مدائن الفهد" },
  { id: "al-jawhara", name: "Al-Jawhara", arabic: "الجوهرة" },
  { id: "al-luyat", name: "Al-Luyat", arabic: "اللؤيات" },
  { id: "taiba", name: "Taiba", arabic: "طيبة" },
  { id: "al-moosa", name: "Al-Moosa", arabic: "الموسى" },
  { id: "al-sawari", name: "Al-Sawari", arabic: "الصواري" },
  { id: "al-amwaj", name: "Al-Amwaj", arabic: "الأمواج" },
  { id: "al-qurayyat", name: "Al-Qurayyat", arabic: "القريات" },
  { id: "al-ashrafieh", name: "Al-Ashrafieh", arabic: "الأشرفية" },
  { id: "al-nozla-al-yamania", name: "Al-Nozla Al-Yamania", arabic: "النزلة اليمانية" },
  { id: "al-nozla-ash-sharqiya", name: "Al-Nozla Ash-Sharqiya", arabic: "النزلة الشرقية" },
  { id: "al-safwa", name: "Al-Safwa", arabic: "الصفوة" },
  { id: "al-thaghr", name: "Al-Thaghr", arabic: "الثغر" },
  { id: "al-ajyad", name: "Al-Ajyad", arabic: "الأجياد" },
  { id: "al-tayseer", name: "Al-Tayseer", arabic: "التيسير" },
  { id: "ar-rayaan", name: "Ar-Rayaan", arabic: "الريان" },
  { id: "umm-as-salam", name: "Umm As-Salam", arabic: "أم السلم" },
]

// Helper function to find district by name (for backward compatibility)
export function findDistrictByName(name: string): District | undefined {
  return JEDDAH_DISTRICTS.find((d) => d.name === name || d.id === name)
}

// Helper function to find district by id
export function findDistrictById(id: string): District | undefined {
  return JEDDAH_DISTRICTS.find((d) => d.id === id)
}
